<?php
declare(strict_types=1);
require dirname(__DIR__) . '/inc/bootstrap.php';
admin_required();

$selectedId = (int)($_GET['selected'] ?? 0);
$listings = $pdo->query('SELECT id, public_id, type, status, title, company_name, created_at FROM listings ORDER BY created_at DESC')->fetchAll();
$interests = $pdo->query("SELECT i.*, l.public_id, l.title FROM interests i JOIN listings l ON l.id=i.listing_id WHERE i.status IN ('new','reviewing') ORDER BY i.created_at DESC")->fetchAll();
$selected = null;
if ($selectedId) {
    $stmt = $pdo->prepare('SELECT * FROM listings WHERE id = ?');
    $stmt->execute([$selectedId]);
    $selected = $stmt->fetch();
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BCE Admin</title><link rel="stylesheet" href="../assets/styles.css"></head>
<body class="admin-body"><header class="admin-header"><div class="brand"><span class="mark">BC</span><strong>BCE Admin</strong></div><a href="../index.php" target="_blank">View site</a><a href="logout.php">Sign out</a></header>
<main class="admin-layout"><aside class="admin-list"><h2>Listings</h2><?php if (!$listings): ?><p class="muted">No submissions yet.</p><?php endif; ?><?php foreach ($listings as $item): ?><a class="admin-list-item <?= $selectedId === (int)$item['id'] ? 'active' : '' ?>" href="?selected=<?= (int)$item['id'] ?>"><span class="status <?= e($item['status']) ?>"><?= e($item['status']) ?></span><strong><?= e($item['public_id'] ?: '#' . $item['id']) ?> · <?= e($item['title']) ?></strong><small><?= e($item['company_name']) ?> · <?= e($item['created_at']) ?></small></a><?php endforeach; ?></aside>
<section class="admin-editor"><?php if ($selected): ?><div class="editor-top"><div><span class="eyebrow"><?= e($selected['type']) ?> submission</span><h1><?= e($selected['public_id'] ?: 'Pending #' . $selected['id']) ?></h1></div><div class="admin-actions"><form method="post" action="action.php"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><?php if ($selected['status'] !== 'published'): ?><button class="btn primary" name="action" value="publish">Approve & publish</button><?php else: ?><button class="btn secondary" name="action" value="pause">Pause</button><button class="btn secondary" name="action" value="close">Close</button><?php endif; ?><button class="btn danger" name="action" value="reject">Reject</button></form></div></div>
<div class="private-box"><strong>Private company data — never shown publicly</strong><p><?= e($selected['company_name']) ?> · <?= e($selected['registration_number']) ?><br><?= e($selected['contact_name']) ?> · <a href="mailto:<?= e($selected['contact_email']) ?>"><?= e($selected['contact_email']) ?></a> · <?= e($selected['contact_phone']) ?></p></div>
<form method="post" action="action.php" class="editor-form"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><div class="form-grid"><label class="wide">Public title<input name="title" value="<?= e($selected['title']) ?>" required></label><label>Country<input name="country" value="<?= e($selected['country']) ?>" required></label><label>City<input name="city" value="<?= e($selected['city']) ?>"></label><label>Industry<input name="industry" value="<?= e($selected['industry']) ?>" required></label><label>People<input type="number" name="people_count" value="<?= e((string)$selected['people_count']) ?>"></label><label class="wide">Specialisations<textarea name="specialisations" required><?= e($selected['specialisations']) ?></textarea></label><label>From<input type="date" name="available_from" value="<?= e($selected['available_from']) ?>"></label><label>Until<input type="date" name="available_until" value="<?= e($selected['available_until']) ?>"></label><label>Duration<input name="duration" value="<?= e($selected['duration']) ?>"></label><label>Languages<input name="languages" value="<?= e($selected['languages']) ?>"></label><label class="wide">Experience / scope<textarea name="experience"><?= e($selected['experience']) ?></textarea></label><label class="wide">Certifications<textarea name="certifications"><?= e($selected['certifications']) ?></textarea></label><label class="wide">Mobility / location<input name="mobility" value="<?= e($selected['mobility']) ?>"></label><label class="wide">Rate information<input name="rate_info" value="<?= e($selected['rate_info']) ?>"></label><label class="wide">Accommodation / travel<input name="accommodation" value="<?= e($selected['accommodation']) ?>"></label><label class="wide">Public description<textarea name="description" rows="5"><?= e($selected['description']) ?></textarea></label></div><button class="btn primary" name="action" value="save">Save changes</button></form>
<?php else: ?><div class="empty-state"><h1>Review queue</h1><p>Select a submission to preview, edit and publish it.</p></div><?php endif; ?>
<section class="interest-panel"><h2>New introduction requests</h2><?php if (!$interests): ?><p class="muted">No new requests.</p><?php endif; ?><?php foreach ($interests as $interest): ?><article><strong><?= e($interest['public_id']) ?> · <?= e($interest['company_name']) ?></strong><p><?= e($interest['contact_name']) ?> · <a href="mailto:<?= e($interest['contact_email']) ?>"><?= e($interest['contact_email']) ?></a><br><?= nl2br(e($interest['message'])) ?></p><form method="post" action="action.php"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$selectedId ?>"><input type="hidden" name="interest_id" value="<?= (int)$interest['id'] ?>"><select name="interest_status"><option value="reviewing">Reviewing</option><option value="introduced">Introduced</option><option value="closed">Closed</option><option value="rejected">Rejected</option></select><button class="btn secondary" name="action" value="interest-status">Update</button></form></article><?php endforeach; ?></section></section></main></body></html>
